version = 1

[[annotations]]
path = [
    "Tests/SpeziStudyTests/Resources/**",
    "Tests/UITests/TestApp/Resources/**"
]
SPDX-FileCopyrightText = "2025 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"